# Generated by Django 5.2.5 on 2025-09-14 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fundacion', models.PositiveIntegerField()),
                ('estadio', models.CharField(max_length=100)),
                ('entrenador', models.CharField(max_length=100)),
                ('presidente', models.CharField(blank=True, max_length=100)),
                ('colores', models.CharField(help_text='Colores del equipo separados por coma', max_length=100)),
                ('titulos_liga', models.PositiveIntegerField(default=0)),
                ('titulos_copa', models.PositiveIntegerField(default=0)),
                ('titulos_internacionales', models.PositiveIntegerField(default=0)),
                ('presupuesto_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo de Fútbol',
                'verbose_name_plural': 'Equipos de Fútbol',
                'ordering': ['nombre'],
            },
        ),
    ]
